### ISSUE TITLE
PresenterManager looses instance

### ISSUE THREAD

**Issue by diogojg** [NikitaKozlov/RetainPresenter#1]
Hi! I am trying out your approach for retaining presenters instances, and I came across with an odd issue. 
Im any fragment, when I rotate the screen and call getPresenter() I am getting a null pointer exception because the presenterManager is null at the time. 

I tried to debug this issue but until this moment I have no clue what this issue could be. The strange thing is that I don't know when the presenterManager looses its instance because I can state that in onResume() the presenterManager has its instance. 

Are you aware of this problem?

Thanks.

**Comment by NikitaKozlov** [comment]
Hi @diogojg! When are you calling `getPresenter()`? PresenterManager is restored during `onCreate()`, so make sure that you call `super` before.
Try to override method `onPresenterRestored()`, to see if it is restored at all.

**Comment by diogojg** [comment]
I'm calling getPresenter() to let the presenter to know that the user pressed a button, so I suppose it's called way after onResume().

**Comment by NikitaKozlov** [comment]
You sure that your activity implements `PresenterActivity`?

**Comment by diogojg** [comment]
Yes, I'm sure. So I did has you said, and overrode onPresenterRestored() and in fact (as I was expecting) the presenter is correctly restored, and I could use getPresenter() with no issues at all. As I stated before, the presenterManager instance is OK until onResume() (at least). After that I don't know. But the fact is, when I press a button at runtime and call getPresenter() the PresenterManager is null and therefore I cannot get the presenter instance. 
I don't know how to debug this, but I'll try because this approach seems very solid and I think it'll worth the effort.

**Comment by diogojg** [comment]
Well, it seems like the problem with getPresenter() only exists when we call it inside an OnClick() (at least). It would be good to know why this happens to fix it. Can you replicate this?

**Comment by NikitaKozlov** [comment]
No, I can't examples do call getPresenter from onClick(). Mb you can create a small project that replicate this crash?

**Comment by diogojg** [comment]
In your code samples there is no example where you call getPresenter(). My question is: every time you need to interact with the presenter do you call getPresenter() or do you save the presenter instance (for example in onStart()) in a variable like "presenter = getPresenter()" and then call presenter.someButtonClicked()?

**Comment by NikitaKozlov** [comment]
True, I only call it from activity, but it should be the same. Check this thing https://github.com/NikitaKozlov/MVP-Navigation/blob/master/app/src/main/java/org/kaerdan/mvp_navigation/example5_retainpresenter/RetainPresenterArticleListFragment.java. I don't save Presenter in member variable.

**Comment by diogojg** [comment]
After some testing and debugging, I've discovered the issue. I had a recyclerViewAdapter which its instance was being restored after rotation. It happens that when it was restored the recycler item clicks were linked to the view that was destroyed before the rotation, so thats why the presenterManager was null in that context.

**Comment by diogojg** [comment]
@NikitaKozlov consider you have a ViewPager where each page is a fragment. As you know, when we slide across the viewPager pages, the fragments in it are destroyed, and we manually need to save and restore the state of the fragments.
The challenge here is how to save and restore the presenter instance (or even simply retain the presenter instance after all). Have you considered to improve your RetainPresenter solution to tackle this issue? Do you have a clean approach regarding this matter?
Thank you!

**Comment by NikitaKozlov** [comment]
I'm glad that you found your issue. Currently I'm not planning to do so, because this is completely out of scope. This library helps your Presenter survive conf changes, but in your case you want to keep presenters for fragments that are destroyed and you don't know if they will be needed at all. So how could you know when Presenter should release it's resources?
